"""
downloader.py — Downloads video files from URLs using yt-dlp.

Priority rules:
  • YouTube  → best vertical (Shorts) quality ≤ 1080p
  • TikTok   → watermark-free format where available, else best quality
  • Instagram→ best quality via yt-dlp
"""

import json
import logging
import re
import shutil
import subprocess
from pathlib import Path

import yt_dlp

logger = logging.getLogger(__name__)

MIN_DURATION = 4
MIN_CLIP_HEIGHT = 480


def _probe_height(path: Path) -> int:
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-select_streams",
                "v:0",
                "-show_entries",
                "stream=height",
                "-of",
                "csv=p=0",
                str(path),
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )
        val = result.stdout.strip()
        return int(val) if val.isdigit() else 0
    except Exception:
        return 0


class Downloader:
    def __init__(self, config):
        self.config = config
        self.out_dir: Path = config.download_dir
        self.out_dir.mkdir(parents=True, exist_ok=True)

    def _load_po_token(self) -> dict:
        """
        Load PO token from data/po_token.json (generated by generate_po_token.mjs).
        Returns extra yt-dlp options for YouTube to bypass bot detection on CI.
        """
        po_path = Path("data/po_token.json")
        if not po_path.exists():
            return {}
        try:
            data = json.loads(po_path.read_text())
            po_token = data.get("po_token", "")
            visitor_data = data.get("visitor_data", "")
            if not po_token or not visitor_data:
                return {}
            return {
                "po_token": po_token,
                "visitor_data": visitor_data,
            }
        except Exception:
            return {}

    def download(self, video: dict) -> Path | None:
        start_time = video.get("start_time")
        end_time = video.get("end_time")

        if start_time is not None and end_time is not None:
            return self._download_segment(video, float(start_time), float(end_time))
        return self._download_full(video)

    def _download_full(self, video: dict) -> Path | None:
        platform = video.get("platform", "unknown")
        url = video["url"]
        vid_id = self._sanitize_id(video["id"])

        existing = self._find_existing(vid_id)
        if existing:
            logger.debug(f"Already downloaded: {existing.name}")
            return existing

        out_template = str(self.out_dir / f"{vid_id}.%(ext)s")
        opts = self._build_ydl_opts(platform, out_template)

        logger.info(f"Downloading {platform} video {vid_id} …")

        try:
            with yt_dlp.YoutubeDL(opts) as ydl:
                info = ydl.extract_info(url, download=True)

                if info is None:
                    logger.warning(f"yt-dlp returned no info for {url}")
                    return None

                duration = info.get("duration") or 0
                if duration and duration < MIN_DURATION:
                    logger.warning(f"Clip too short ({duration}s), skipping {vid_id}")
                    self._cleanup(vid_id)
                    return None

            downloaded = self._find_existing(vid_id)

            if downloaded:
                h = _probe_height(downloaded)

                if h and h < MIN_CLIP_HEIGHT:
                    logger.warning(
                        f"Clip too low-res ({h}p < {MIN_CLIP_HEIGHT}p), skipping {vid_id}"
                    )
                    self._cleanup(vid_id)
                    return None

                logger.info(f"✓ {downloaded.name} [{h}p]" if h else downloaded.name)
                return downloaded

            logger.warning(f"Download finished but file missing for {vid_id}")
            return None

        except yt_dlp.utils.DownloadError as e:
            logger.warning(f"Download failed for {url}: {e}")
            self._cleanup(vid_id)
            return None

        except Exception as e:
            logger.error(f"Unexpected error downloading {url}: {e}")
            self._cleanup(vid_id)
            return None

    def _download_segment(self, video: dict, start: float, end: float) -> Path | None:
        platform = video.get("platform", "youtube")
        url = video["url"]
        vid_id = self._sanitize_id(video["id"])

        existing = self._find_existing(vid_id)
        if existing:
            return existing

        out_template = str(self.out_dir / f"{vid_id}.%(ext)s")
        opts = self._build_ydl_opts(platform, out_template)

        opts["download_ranges"] = yt_dlp.utils.download_range_func(
            chapters=None,
            ranges=[(start, end)],
        )

        opts["force_keyframes_at_cuts"] = True

        try:
            with yt_dlp.YoutubeDL(opts) as ydl:
                ydl.extract_info(url, download=True)

            downloaded = self._find_existing(vid_id)

            if downloaded:
                h = _probe_height(downloaded)

                if h and h < MIN_CLIP_HEIGHT:
                    self._cleanup(vid_id)
                    return None

                return downloaded

            return None

        except Exception as e:
            logger.warning(f"Segment download failed {url}: {e}")
            self._cleanup(vid_id)
            return None

    def download_batch(self, videos: list[dict], target: int) -> list[tuple[dict, Path]]:
        results = []

        for video in videos:
            if len(results) >= target:
                break

            path = self.download(video)

            if path:
                results.append((video, path))

        return results

    def _build_ydl_opts(self, platform: str, out_template: str) -> dict:

        base = {
            "outtmpl": out_template,
            "quiet": True,
            "no_warnings": True,
            "ignoreerrors": False,
            "nocheckcertificate": True,
            "merge_output_format": "mp4",

            # network stability
            "socket_timeout": 30,
            "retries": 3,
            "fragment_retries": 3,

            # reduce bot detection
            "sleep_interval": 3,
            "max_sleep_interval": 6,

            # mobile client user agent
            "http_headers": {
                "User-Agent": "com.google.android.youtube/19.09.37 (Linux; Android 11)"
            },

            # post processing
            "postprocessors": [
                {
                    "key": "FFmpegVideoConvertor",
                    "preferedformat": "mp4",
                }
            ],
        }

        if platform == "youtube":

            base["format"] = (
                "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]"
                "/bestvideo[height<=1080]+bestaudio"
                "/best[height<=1080]"
                "/best"
            )

            po = self._load_po_token()
            if po:
                # PO token available (GitHub Actions) — use web client
                base["extractor_args"] = {
                    "youtube": {
                        "po_token": [f"web+{po['po_token']}"],
                        "player_client": ["web"],
                    }
                }
                base["http_headers"] = {
                    **base.get("http_headers", {}),
                    "X-Goog-Visitor-Id": po["visitor_data"],
                }
            else:
                # No PO token (local dev) — use android client
                base["extractor_args"] = {
                    "youtube": {
                        "player_client": ["android", "tv_embedded"]
                    }
                }

        elif platform == "tiktok":

            base["format"] = (
                "download_addr-0/play_addr-0"
                "/bestvideo[ext=mp4]+bestaudio[ext=m4a]"
                "/best[ext=mp4]/best"
            )

            base["extractor_args"] = {
                "tiktok": {
                    "webpage_download": False
                }
            }

        elif platform == "instagram":

            base["format"] = "best[ext=mp4]/best"

        else:

            base["format"] = "best[height<=1080]/best"

        return base

    def _sanitize_id(self, vid_id: str) -> str:
        return re.sub(r"[^A-Za-z0-9_\-]", "_", vid_id)[:60]

    def _find_existing(self, vid_id: str) -> Path | None:
        for ext in ("mp4", "webm", "mkv", "mov"):
            p = self.out_dir / f"{vid_id}.{ext}"
            if p.exists() and p.stat().st_size > 10000:
                return p
        return None

    def _cleanup(self, vid_id: str):
        for p in self.out_dir.glob(f"{vid_id}.*"):
            try:
                p.unlink()
            except Exception:
                pass
